### PR TITLE
Update visualization_tutorial.rst

### PR DESCRIPTION
**Pull request by 0ldham**
Leads to an out-of-date page.

### CODE REVIEW

**Comment by jbohren** [comment]
@oliviao00 Can you see what you need to do to update that tutorial to use `gazebo_ros_pkgs`? Try to run through it as-is, and document _exactly_ what's broken. Then try to create a new `.rst` file in this repository with a fixed version of that tutorial.

@davetcoleman should be able to give you guidance on migrating it.

**Comment by oliviao00** [comment]
@jbohren The page is out-of-date because it is based on Indigo and all the previous tutorials are based in Kinetic.  I would revise it for Kinetic but the pr2_simulator isn't developed for Kinetic yet.

**Comment by davetcoleman** [comment]
The wiki was taken down from its original location a few years ago by someone, but I had a lot of useful documentation still on there so I restored the wiki on my own website so the links were dead. I would like to remove all these old links, yes, but first we should copy the missing documentation and tutorials back to moveit.ros.org and the moveit_tutorials. @oliviao00 do you think you could do that? It would largely be searching to see if the information was copied over (a lot of it was not) then creating a PR with a copy-pasted version of the old docs. Then we can permanently kill the wiki.

**Comment by 0ldham** [comment]
@davetcoleman I've sorted through the tutorials and documentation and started creating commits of those pages for the tutorials and moveit.ros.org, and revising as I go.  There are some that would be best integrated into certain tutorials, but for now I'll leave them separate.

**Pull request closed without merging**
