### PR TITLE
Tutorial fixes

### PR DESCRIPTION
**Pull request by jwhendy**
Primary fix was a wording change on `Show Robot Visual`. Also added a screenshot of adding the `Interact` button at the top; mine wasn't initially there and hung me up for 5min trying to find it. Thought it would help other noobs to RViz. Addresses #89

### CODE REVIEW

**Comment by v4hn** [comment]
lgtm.

Usually the interact tool should be there by default, so I don't know how you managed to remove it.
Thanks for the added hint though, maybe it can help someone else.

**Comment by v4hn** [comment]
Welcome to the community then and thanks for starting out with contributions right away 👍

**Comment by davetcoleman** [comment]
+1!!

**Comment by jwhendy** [comment]
Noticed that #92 removed the image on how to add the interact button. Following back up to see if that's desirable to have. I noted that `roslaunch pr2_moveit_config moveit_rviz.launch` gives me the button, but `demo.launch` does not. (If that helps understand behavior at all.)

If it shouldn't exist in this tutorial, maybe it should exist somewhere (an overall RViz guide)? Just giving feedback that as a complete noob I was hung up for ~15min on where the tutorial meant to click on said interact button before it dawned on me to click the + sign!

**Pull request merged**
