### PR TITLE
[html layout] Improve the format

### PR DESCRIPTION
**Pull request by 130s**
Improvement to the https://github.com/ros-planning/moveit_tutorials/pull/68#issuecomment-285948136
img

I'm not entirely sure if this PR works better but I have no way to test how it renders other than opening try&error PR like this..

### CODE REVIEW

**Comment by davetcoleman** [comment]
The README of this repo documents how to build the tutorials locally so you can open the HTML page before submitting a PR

**Comment by davetcoleman** [comment]
screenshot from 2017-03-12 19-01-12

Still not good

**Comment by davetcoleman** [comment]
This works:

>                 <div class="highlight-c++">
>                   <div class="highlight">
>                     <pre>git clone https://github.com/ros-planning/moveit_tutorials
>     cd moveit_tutorials/doc
>     git checkout indigo-devel</pre>
>                   </div>
>                 </div>

Though thinking about it more, I think you are babying the users too much at the top of *every* tutorial page. Why not just leave the first sentence that provides the link to Github and specify to use the indigo branch?

**Comment by 130s** [comment]
> you are babying the users too much at the top of every tutorial page. Why not just leave the first sentence that provides the link to Github and specify to use the indigo branch?

Ok, I also thought the previous one is a bit too long. How's this?
screenshot from 2017-03-13 16 25 45

**Comment by davetcoleman** [comment]
that's succinct, perfect!

**Pull request merged**
