### PR TITLE
Update README with gif admonition

### PR DESCRIPTION
**Pull request by DLu**
### Description

Followup to #550 

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by rhaschke — COMMENTED** [review]
The link refers to rather generic documentation of the raw feature. I think it would be helpful to provide a concrete example of how to embed, both a youtube video and a .webm video.

**Comment by DLu** [comment]
I thought about doing that, but we also don't include examples of how to include images. I figured people would just grep through.

**Comment by rhaschke** [comment]
> I thought about doing that, but we also don't include examples of how to include images. I figured people would just grep through.

In principle I would agree. But the referred page doesn't give an example how to embed a video. So the link doesn't help much.

**Review by davetcoleman — APPROVED** [review]
I like the level of detail here. Per Robert's concern, maybe link to an example in this repo

**Review by felixvd — APPROVED** [review]
I like the level of detail *now*.

**Review by rhaschke — APPROVED** [review]

**Pull request merged**
