### PR TITLE
Add description how to add duration parameters in controller manager tutorial

### PR DESCRIPTION
**Pull request by 2scholz**
This is in relation to https://github.com/ros-planning/moveit/pull/785

I added an example of how to set these parameters. 

I also added a description that details what these parameters do, due to the fact that I could not find any previous documentation of them in any of the tutorials.

### CODE REVIEW

**Comment by v4hn** [comment]
Hm, I don't think these parameters are relevant for the fake controller manager, so this feels like the wrong place for this information.
Could you add it [here](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pr2_tutorials/planning/src/doc/controller_configuration.html) instead?

**Comment by v4hn** [comment]
> I added the parameters to the existing YAML file examples

That sounds like a good idea at first, but please don't.
These parameters are optional and the defaults are good enough for almost all users.
I think you already have a rough idea how confused most newcomers are by MoveIt's complexity, no need to fire an even longer `yaml` at them (at first).
So this deserves its own section below, possibly with its own example.

**Comment by 2scholz** [comment]
I made the suggested changes and added a short example.

**Comment by 2scholz** [comment]
I added a short description of the differences between the controller-specific values and the global ones. 
I also rebased the branch, because the file was moved to a different directory recently.

**Comment by v4hn** [comment]
Thanks @2scholz !

**Pull request merged**
