### PR TITLE
fixed collision contact tutorial failing build due to image location…

### PR DESCRIPTION
**Pull request by jwhendy**
… and not being referenced by a toctree

I kept getting failures on a pretty simple PR (#93) and found it's related to #87 . This fixes (well, at least one way to do it) two issues I found:

- image path was `/ros_visualization/collision_contact_tutorial_screen.png` and I think that hard path was wrong. I didn't get it to play nicely, so I moved it into the same folder as the `.rst` (`doc/`) like all of the other tutorial image files

- after fixing that, I was getting a failure related to this tutorial not being referenced by a `toctree`. I found [this SO post](https://stackoverflow.com/questions/15249340/warning-document-isnt-included-in-any-toctree-for-included-file) saying one could add `:orphan:` to the top of the file.

If this *is* desired in some table of contents, I'll leave that to someone else to fix. This just gave some peace of mind as I thought my PR was causing an issue...

### CODE REVIEW

**Comment by jwhendy** [comment]
Instead of using the `:orphan:` trick, it dawned on me that this might not add the tutorial anywhere. I added it to `index.rst` and removed `:orphan:` so hopefully that does the trick.

**Comment by 0ldham** [comment]
My mistake!  Thanks for the PR; looks good.

**Comment by davetcoleman** [comment]
@jwhendy thanks for correcting this. The errors from our CI builds are currently difficult because it has a valid URL checker that always when new tutorials or image assets are added. This is because it checks the *current* website for those files, when in fact the files won't exist until after the PR is merged. Because of this, I have to merge PRs even when travis fails based on visual inspection of the reasons it failed, which can be error prone. If you had motivation to improve our CI, it would be great to have it run tests on the *new* website (including changes) rather than the current one.

**Comment by jwhendy** [comment]
I *think* I follow that? Basically if someone adds some file to `/path/to/file.ext`, it doesn't exist yet and thus the build fails no matter what. Then you merge, the file gets created, and *then* you get the real feedback on the build. Is that halfway accurate?

I have zero Cl experience, but seems pretty great especially for a huge project like ROS! I may add it to my mental "someday to look into" list!

**Pull request merged**
