### PR TITLE
update arm_jogging_tutorial.rst due to the change of the package name

### PR DESCRIPTION
**Pull request by Smilels**
since the name of moveit_jog_arm is moveit_servo now, it's better to update the tutorial page.

### CODE REVIEW

**Review by felixvd — APPROVED** [review]
LGTM, but @AndyZe should have a look

**Comment by AndyZe** [comment]
Thanks for the PR! It's basically a copy of this one, that should have been merged a long time ago:

https://github.com/ros-planning/moveit_tutorials/pull/508

**Comment by AndyZe** [comment]
I will ping some maintainers to get one of these PR's merged today.

**Comment by AndyZe** [comment]
I think I'll close this since the other PR got merged. Please re-open it if the new version has errors

**Pull request closed without merging**
