### PR TITLE
Add Python2 compatibility

### PR DESCRIPTION
**Pull request by felixvd**
Our move_group Python Interface tutorial uses some Python3-exclusive functions, but our master branch builds on Kinetic and Melodic, where Python2 is the standard. These changes allow running the tutorial in Python 2.7.

### Checklist
- [X] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
Being backwards compatible is really nice.  Thank you for this.

I'm not sure if we are the right ones to try to convince users of this, but if they are using Melodic on 18.04 python2 is EOL and they should install python3 and configure their system to use it.  Kinetic itself is EOL and users should probably not be using it.  That being said, the errors that this would produce are not a nice way to tell users that.

**Comment by gavanderhoorn** [comment]
@tylerjw wrote:
> I'm not sure if we are the right ones to try to convince users of this, but if they are using Melodic on 18.04 python2 is EOL and they should install python3 and configure their system to use it

and then run into endless problems with ROS packages having been built and linked to the system Python 2 (I'm looking at you `cv_bridge`, but there are others)?

This isn't going to work, certainly not for new users, who have trouble enough as it is figuring out ROS.

**Comment by tylerjw** [comment]
In that case should ROS EOL Melodic or strongly discourage it somehow because it has a strong dependency on python2 (via 18.04 and all the released python code in Melodic)?

**Comment by gavanderhoorn** [comment]
> In that case should ROS EOL Melodic or strongly discourage it somehow because it has a strong dependency on python2 (via 18.04 and all the released python code in Melodic)?

ROS Discourse: [Some things to know as Python 2 approaches EOL](https://discourse.ros.org/t/some-things-to-know-as-python-2-approaches-eol/11175).

It is still supported.

So no need to do anything.

Whether newcomers should still use it is a different discussion.

**Comment by tylerjw** [comment]
> All those _newfangled_ deeplearning libraries/frameworks require Python 3 most of the time anyway, so I expect this to solve itself.

:laughing: good point, this is why all the cool kids are using python anyway.

**Comment by felixvd** [comment]
Newer libraries not working in Python2 is the reason that migration came up in one of my projects. But colleagues also told me that they were at an exhibition and high schoolers laughed about them using Python 2, so there's that kind of pressure as well.

FWIW, I caught this when I was testing #617 on moveit's `master-source` container, which is on Ubuntu 18.04 for some reason. Maybe it's time we switch that to `noetic-source`.

**Comment by gavanderhoorn** [comment]
> But colleagues also told me that they were at an exhibition and high schoolers laughed about them using Python 2, so there's that kind of pressure as well.

Perhaps your colleagues didn't laugh at the high-schoolers hard enough in return.

I find it's a sign of immaturity to mock the design / implementation choices of another developer without knowing his or hers motivation for those choices.

I doubt those "high-schoolers" have ever developed an actual product, or have had to support an existing product or *project*.

Legacy is a thing, and except for startups which are very young, I doubt there are companies which don't maintain at least some legacy somewhere.

**Comment by mikeferguson** [comment]
> Legacy is a thing, and except for startups which are very young, I doubt there are companies which don't maintain at least some legacy somewhere.

Ha - that's funny. In my experience, startups more than a few months old quickly have lots of legacy (especially in robotics) because they lack the manpower needed to keep migrating to newer versions and they often haven't properly planned for major field updates on shipped product.

**Comment by gavanderhoorn** [comment]
> Ha - that's funny. In my experience, startups more than a few months old

that's why I wrote "*very* young" ;)

**Comment by felixvd** [comment]
> Ha - that's funny

Your response already contains more text than this PR, so you are now honor-bound to review it

> I find it's a sign of immaturity to mock the design / implementation choices of another developer without knowing his or her motivation for those choices.

True. High school students.

**Review by mikeferguson — APPROVED** [review]

**Comment by mikeferguson** [comment]
> Your response already contains more text than this PR, so you are now honor-bound to review it

Fair enough.

**Review by v4hn — APPROVED** [review]

**Pull request merged**
