### PR TITLE
Add a note about the index to the README.

### PR DESCRIPTION
**Pull request by AndyZe**
A small note about adding your tutorial to index.rst, and fixing one typo.

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by davetcoleman** [comment]
Not your fault but can you fix the chomp link, it moved in the moveit repo. See Travis output. New location:

https://github.com/ros-planning/moveit/blob/melodic-devel/moveit_planners/chomp/chomp_optimizer_adapter/src/chomp_optimizer_adapter.cpp

**Comment by AndyZe** [comment]
It looks like Travis ignored my changes on that last commit (f9b344d). Weird. Re-trigger it?

**Comment by davetcoleman** [comment]
Its a different page you still missed: doc/planning_adapters/planning_adapters_tutorial.html

**Comment by davetcoleman** [comment]
@AndyZe i just noticed you targeted the kinetic branch. In the future please make changes to latest (Melodic) unless you have a really compelling reason not to. Cherry picking

**Pull request merged**
