### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by vatanaksoytezer**
Recently moveit_core api documentation has been moved from html/ to html/cpp, which was causing links to break and CI to fail on checking links.

For example: http://docs.ros.org/en/noetic/api/moveit_core/cpp/namespacecollision__detection__bullet.html moved to http://docs.ros.org/en/noetic/api/moveit_core/html/cpp/namespacecollision__detection__bullet.html

This PR fixes those broken links.

### CODE REVIEW

**Review by MarqRazz — APPROVED** [review]

**Review by v4hn — APPROVED** [review]

**Comment by v4hn** [comment]
Thanks for the adjustment!

I expect [the recent addition of python bindings in moveit_core](https://github.com/ros-planning/moveit/pull/2547) entailed this change. Quite unfortunate, but I can see why it's implemented that way.

**Comment by vatanaksoytezer** [comment]
Yeah, probably the links where changed after the new python bindings. Had to apply similar fixes in moveit2_tutorials as well here: https://github.com/ros-planning/moveit2_tutorials/pull/71

**Comment by rhaschke** [comment]
We could have solved the broken links by changing the output folder for cpp docs as well [here](https://github.com/ros-planning/moveit/blob/3361b2d1b6b2feabc2d3e93c75653f5a00e87fa4/moveit_core/rosdoc.yaml#L6). Probably moveit_tutorials are not the only location left with broken links?

**Comment by vatanaksoytezer** [comment]
@rhaschke i've already fixes the broken ones in moveit2_tutorials and moveit.ros.org. I didnt find any where else yet. At least it does not seen yo bother the CIs in other repos

**Comment by v4hn** [comment]
> We could have solved the broken links by changing the output folder for cpp docs as well here.

Yes, but then we would have overlapping folders for c++ and python documentation and that's not good either.
Thanks for pointing out it was a deliberate decision by you/Peter.

**Pull request merged**
