### PR TITLE
correct explanation of padding parameters

### PR DESCRIPTION
**Pull request by v4hn**
@lianghongzhuo pointed out to me that the explanation was insufficient and when I looked it turned out to be wrong too...

### CODE REVIEW

**Comment by lianghongzhuo** [comment]
Actually, we find that `padding scale` was considered as `min range` in the ocotomap. if setting padding scale to 1, rviz will only show ocotomap far than 1 meter

**Comment by v4hn** [comment]
I believe you're wrong. We will discuss/debug this offline.

**Comment by v4hn** [comment]
Turns out, @lianghongzhuo found a bug in MoveIt's pointcloud_octomap_updater . I will file an issue in the main repository.

This is independent of this pull-request though.

**Review by lianghongzhuo — APPROVED** [review]
This pull request has a more clear explanation than the previous one. And fix the wrong unit (cm -> m)

**Pull request merged**
