### PR TITLE
[visualization_tutorial] Add trajectory slider

### PR DESCRIPTION
**Pull request by 130s**
I believe how to use https://github.com/ros-planning/moveit/pull/491 isn't documented anywhere yet (took me awhile to figure it out).

Should be portable to `indigo-devel`. In fact I took the snapshot on Indigo.

### CODE REVIEW

**Comment by v4hn** [comment]
@130s testing failed

**Comment by 130s** [comment]
https://travis-ci.org/ros-planning/moveit_tutorials/builds/242549355#L976
```
The command "sphinx-build -W -b html . native_build" exited with 1.
0.19s$ rosdoc_lite -o build .
Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rosdoc_lite", line 37, in <module>
    rosdoc_lite.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosdoc_lite/__init__.py", line 225, in main
    pkg_desc = get_pkg_desc(path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosdoc_lite/__init__.py", line 241, in get_pkg_desc
    pkg_desc = packages.parse_package(path)
AttributeError: 'module' object has no attribute 'parse_package'
```

I think this is related to changes somewhere upstream and in `rosdoc_lite` it's already addressed (e.g. https://github.com/ros-infrastructure/rosdoc_lite/pull/74) but its new version that includes the fixes are [not yet synced for Indigo](http://repositories.ros.org/status_page/ros_indigo_default.html?q=rosdoc) as of today. [Indigo sync happened 2 weeks ago](https://discourse.ros.org/t/new-packages-for-indigo-2017-06-01/1887/1) so hopefully next sync will be made soon. Then we can restart the CI job.

**Comment by v4hn** [comment]
Oh, it's two errors then. I didn't see the one you pointed out :D

I saw only the other one at first glance:
> /home/travis/build/ros-planning/moveit_tutorials/doc/ros_visualization/visualization_tutorial.rst:168: WARNING: Inline interpreted text or phrase reference start-string without end-string.

**Comment by 130s** [comment]
@v4hn Thanks for catching that. Now it should be fixed.

For `rosdoc_lite`, I [asked for when's the next sync](https://discourse.ros.org/t/preparing-for-indigo-sync-2-in-2017-06/1953/1).

**Comment by v4hn** [comment]
I don't want to have this hanging here until upstream fixed the package, so I'll merge it.

**Comment by davetcoleman** [comment]
Great documentation, thanks!

**Comment by 130s** [comment]
Ported to indigo-devel https://github.com/ros-planning/moveit_tutorials/commit/5a3816bea0e1d51acafea1e88b47ecdcf35bdfdd

**Pull request merged**
