### PR TITLE
Change planning_scene topic in RViz tutorial

### PR DESCRIPTION
**Pull request by tylerjw**
This fixes a typo in the RViz tutorial.  You can see that the topic is `move_group/monitored_planning_scene` in the image.  If you change it to be `/planning_scene` it breaks later steps in the tutorial.  Executing plans created by dragging around the marker doesn't work if you change this.

### CODE REVIEW

**Comment by felixvd** [comment]
I can confirm that the `/planning_scene` topic is outdated and execution is not displayed properly if that topic is set.

The line further down ("* In **Planned Path**, change the **Trajectory Topic** to ``/move_group/display_planned_path``.") should be changed to "* Make sure the **Planned Path** is set to ``/move_group/display_planned_path``.", since that value is already set.

Also, the images are pretty old. How about replacing the first screenshots with 
[these](https://user-images.githubusercontent.com/4535737/94999180-a4339300-05f2-11eb-987e-9daef8509e87.png) [two](https://user-images.githubusercontent.com/4535737/94999179-a1d13900-05f2-11eb-9621-a29c6a6a8b81.png).

**Review by felixvd — APPROVED** [review]
I'd also add the changes mentioned, but it's good to go as is, too.

**Comment by tylerjw** [comment]
@felixvd you are a maintainer and I used my fork so you should be able to just push to the branch for this PR for your changes.  They make sense to me, reword that second section, and update the images.  Thank you for the review.

**Comment by felixvd** [comment]
Right. I'll go ahead and merge this.

**Pull request merged**
