### PR TITLE
fix issues #505 wrong transform for the perception pipeline tutorial

### PR DESCRIPTION
**Pull request by lianghongzhuo**
### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by lianghongzhuo** [comment]
As described in https://github.com/ros-planning/moveit_tutorials/issues/505 
The rviz can not properly show point cloud and octomap. The problem is that in the launch file the transform is not set correctly. So the moveit complains that it can not find correct transform to world.

**Comment by lianghongzhuo** [comment]
Just saw https://github.com/ros-planning/moveit_tutorials/pull/491 has fixed this in master branch, but maybe still relevant if people are using melodic branch version tutorial?

**Comment by rhaschke** [comment]
I suggest cherry-picking #491 instead of applying a different patch here. I will shortly test and then proceed like this...

**Comment by rhaschke** [comment]
I back-ported #491, which perfectly solves the problem. Thanks for hinting at the problem and the solution!

**Pull request closed without merging**
