### PR TITLE
Remove redundant steps

### PR DESCRIPTION
**Pull request by mlautman**
moveit.rosinstall includes panda_moveit_config and moveit_tutorials making cloning them by hand redundant

### CODE REVIEW

**Comment by rhaschke** [comment]
You are right. I just trusted the Mike's statement, which seems to be wrong indeed.

**Comment by mlautman** [comment]
>> moveit.rosinstall includes panda_moveit_config

> As far as I can see this statement is wrong and I would prefer to keep it that way.

Hrm, not sure how I made that mistake. moveit_tutorials is however in the rosinstall. I think @rhaschke's suggestion of making a moveit_tutorials.rosinstall makes sense here

**Comment by mlautman** [comment]
accidentally closed pr by dropping all new changes. Reopening

**Comment by mlautman** [comment]
Closing because stale

**Pull request closed without merging**
