### PR TITLE
Fix some issues with the Benchmarking tutorial

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Ok, conflicts resolved.

If someone else from @ros-planning/moveit-developers could review and merge it?

Note that I can't push updates to the `gh-pages` branch right now, so if 'someone' could do that as well, that would be appreciated.

**Comment by v4hn** [comment]
thanks. merged.

**Comment by davetcoleman** [comment]
thanks @gavanderhoorn !

also if you're going to push branches directly to the repo, please don't forget to delete them when the PR is closed

**Comment by gavanderhoorn** [comment]
My apologies. I never intended for that branch to end up on the main repository. The web-based direct editing UI of Github doesn't make it too clear where things go though.

**Pull request merged**
