### PR TITLE
little typo

### PR DESCRIPTION
**Pull request by robbycandra**

### CODE REVIEW

**Comment by robbycandra** [comment]
Hi @v4hn, 

Because the comment say **// down and right (back to start)**
I see that indigo branch has that line but it disappear in kinetic branch. 

Indigo branch :

```

geometry_msgs::Pose target_pose3 = start_pose2;
  target_pose3.position.x += 0.2;
  target_pose3.position.z += 0.2;
  waypoints.push_back(target_pose3);  // up and out

  target_pose3.position.y -= 0.2;
  waypoints.push_back(target_pose3);  // left

  target_pose3.position.z -= 0.2;
  target_pose3.position.y += 0.2;
  target_pose3.position.x -= 0.2;
  waypoints.push_back(target_pose3);  // down and right (back to start)
```

**Comment by v4hn** [comment]
ping @davetcoleman ? What happened to that line?

**Comment by davetcoleman** [comment]
That location was unreachable and so the Cartesian trajectory was not able to complete the entire waypoint path. I should have updated the comments to reflect the change but missed that.

@robbycandra can you, instead of re-instating the x component modification, just update the comment instead?

**Comment by robbycandra** [comment]
@davetcoleman ok. Please check.

TQ,

**Comment by v4hn** [comment]
Merged, thanks again!

**Pull request merged**
