### PR TITLE
Create stub gazebo simulation tutorial

### PR DESCRIPTION
**Pull request by davetcoleman**
Starts to address https://github.com/ros-planning/moveit_tutorials/issues/128

### CODE REVIEW

**Comment by davetcoleman** [comment]
@mlautman for re-review

**Comment by tahsinkose** [comment]
I'm working on this.

**Comment by davetcoleman** [comment]
@tahsinkose not sure how to best give you write access to a branch, but I'd rather you just create a new PR directly to moveit_tutorials that replaces this (but it can still include my commit, also)

**Comment by tahsinkose** [comment]
@davetcoleman I just wanted to avoid duplication. Anyways I'll open a new PR then :+1:

**Pull request closed without merging**
