### PR TITLE
MoveItCpp Tutorial

### PR DESCRIPTION
**Pull request by JafarAbdi**
### Description

I mistakenly deleted my fork in the past and the open PR show unknown repository,

This contains the addressed review from the previous [PR](https://github.com/ros-planning/moveit_tutorials/pull/397)

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by davetcoleman** [comment]
@JafarAbdi now that the main feature is merged, please resolve conflicts and lets merge this!

**Comment by JafarAbdi** [comment]
@davetcoleman I just resolved the merge

**Comment by davetcoleman** [comment]
> /root/ros_ws/src/moveit_tutorials/doc/moveit_cpp/src/moveit_cpp_tutorial.cpp:4:10: fatal error: moveit/moveit_cpp/moveit_cpp.h: No such file or directory
 #include <moveit/moveit_cpp/moveit_cpp.h>

We just merged it though?

**Comment by davetcoleman** [comment]
Maybe a Docker cache is being used?

**Comment by JafarAbdi** [comment]
I just trigger a build, it should work now, seems like the master-source docker image wasn't didn't contains the moveit_cpp commits

**Comment by JafarAbdi** [comment]
I just triggered a new build, it should work now, seem like the master-source docker image didn't include the moveit_cpp changes but now they exist in the docker image

**Pull request merged**
