### PR TITLE
Remove inorder tag because it produced warning in ROS Melodic now

### PR DESCRIPTION
**Pull request by davetcoleman**
Fix warning in terminal:

> xacro: in-order processing became default in ROS Melodic. You can drop the option.

### CODE REVIEW

**Comment by v4hn** [comment]
Wouldn't this break support for ROS kinetic for no reason at all?

I fail to see why they added a "be backward-incompatible" warning in xacro.
The unix standard would be to keep it around as a quiet no-op.

**Comment by rhaschke** [comment]
> I fail to see why they added a "be backward-incompatible" warning in xacro.
The unix standard would be to keep it around as a quiet no-op.

I can fix this in xacro as well. However, without this hint, the unnecessary `--inorder` options will never get cleaned up...

**Comment by gavanderhoorn** [comment]
> > I fail to see why they added a "be backward-incompatible" warning in xacro.
> > The unix standard would be to keep it around as a quiet no-op.
> 
> I can fix this in xacro as well. However, without this hint, the unnecessary `--inorder` options will never get cleaned up...

I'd like `--inorder` to be a no-op, as @v4hn suggests.

As the new behaviour has become the default, the option is no needed, but it also doesn't break anything to simply ignore it: xacros loaded with it will still be parsed correctly. Emitting warnings for things that are essentially not problematic makes users (incorrectly) assume something is wrong.

**Comment by rhaschke** [comment]
I think, emitting an info message, would be the correct approach then. Do you agree?

**Comment by v4hn** [comment]
> I can fix this in xacro as well. However, without this hint, the unnecessary `--inorder` options will never get cleaned up...

I don't believe it's your job as maintainer of upstream to enforce that people clean up *their* code base, as long as it does not introduce problems. ;)
Either way I would definitely not expect this warning in melodic already, as some people try to manage kinetic/melodic compatible projects.

**Comment by gavanderhoorn** [comment]
I don't believe I have such strong feelings as @v4hn about this, but would simply not printing anything be acceptable for you @rhaschke?

**Comment by rhaschke** [comment]
I'm not enforcing people to cleanup their code. I just want to provide a reminder to do so ;-)
So, silently ignoring the (deprecated) option is not an option for me.

**Comment by davetcoleman** [comment]
> Either way I would definitely not expect this warning in melodic already, as some people try to manage kinetic/melodic compatible projects.

I agree with @v4hn that its too soon for this warning.

I made this PR because I believe ignoring warnings (and errors) is really bad practice. But this warning seems to be a false alarm

**Comment by davetcoleman** [comment]
@rhaschke can you make this an INFO message for now, instead of a warning? then we can close this PR without merging

**Comment by rhaschke** [comment]
I reduced to an info message in xacro. I think, this fix should be applied to the master branch anyway.

**Comment by davetcoleman** [comment]
Great, merging.

**Pull request merged**
