### PR TITLE
Update move_group_python_interface_tutorial.py

### PR DESCRIPTION
**Pull request by mqnc**
test:
```
import numpy as np
from scipy.spatial.transform import Rotation as R
from moveit_commander.conversions import list_to_pose

for i in range(10000):
  rot0 = R.random()
  axis = np.random.rand(3)
  axis = axis / np.linalg.norm(axis)
  angle = 0.01

  rot1 = rot0 * R.from_rotvec(axis * angle)

  assert all_close(
    list_to_pose([0,0,0] + list(R.as_quat(rot0))),
    list_to_pose([0,0,0] + list(R.as_quat(rot1))),
    angle + 1e-8
  )

  assert not all_close(
    list_to_pose([0,0,0] + list(R.as_quat(rot0))),
    list_to_pose([0,0,0] + list(R.as_quat(rot1))),
    angle - 1e-8
  )

  # check with negative quaternion
  assert all_close(
    list_to_pose([0,0,0] + list(R.as_quat(rot0))),
    list_to_pose([0,0,0] + list(-R.as_quat(rot1))),
    angle + 1e-8
  )

  assert not all_close(
    list_to_pose([0,0,0] + list(R.as_quat(rot0))),
    list_to_pose([0,0,0] + list(-R.as_quat(rot1))),
    angle - 1e-8
  )
```

### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by rhaschke — APPROVED** [review]
Thanks for this contribution.

**Comment by rhaschke** [comment]
Fixes #574

**Review by felixvd — APPROVED** [review]
Only fixed documentation and typos, will merge when the build passes. I didn't know about this edge case, so I'm sure this will be helpful. Thanks for the contribution!

**Comment by mlautman** [comment]
Thanks @mqnc

**Pull request merged**
