### PR TITLE
Start tutorial for using CHOMP

### PR DESCRIPTION
**Pull request by davetcoleman**
Also clarified "stub tutorial"

### CODE REVIEW

**Comment by davetcoleman** [comment]
once merged https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_planners/chomp/README.md should be deleted

**Comment by davetcoleman** [comment]
Again travis can be ignored:

>   *  External link https://github.com/ros-planning/moveit_tutorials/blob/kinetic-devel/doc/chomp_interface_tutorial.rst failed: 404 No error

**Comment by davetcoleman** [comment]
ping

**Comment by v4hn** [comment]
Why do you want to merge stubs as upstream documentation?
If anyone wants to turn them into proper tutorials, they can just fork your branch and afterwards request to merge the results upstream.

What is the merit of merging this as-is?

**Comment by davetcoleman** [comment]
1) I thought it would be more, because I was transferring the README.md. However once I copied that file, I realized most of its content was not useful
2) This still provides documentation for the roslaunch file
3) Having the page created I think encourages others who decide to try CHOMP to extend it who

**Comment by v4hn** [comment]
ok, sounds reasonable.

**Pull request merged**
