### PR TITLE
fixing the order of the voxels in the image

### PR DESCRIPTION
**Pull request by mlautman**
### Description
Fixes the order of the suction voxels

### CODE REVIEW

**Comment by mlautman** [comment]
@Dale-Koenig

**Comment by Dale-Koenig** [comment]
I really thing the labeling here should be the same as used by `getSuctionVoxel` (and therefore 0 indexed).  Is there anywhere in the code that starts indexing at 1?

**Comment by mlautman** [comment]
@Dale-Koenig fixed

**Comment by Dale-Koenig** [comment]
> @Dale-Koenig fixed

Thanks!

**Pull request merged**
