### PR TITLE
Adding tutorial home link

### PR DESCRIPTION
**Pull request by simonGoldstein**
### Description

*This is functionally identical to #345 but for the master branch.*

Most websites have the behavior that if you click on the logo, it returns to the main page of the website. That’s a standard across most websites, and users are used to that. The MoveIt website follows this pattern (on all of the subpages) where if you click the MoveIt logo it returns you to the MoveIt homepage; the one exception, is when you go to the tutorials, which is listed in the MoveIt header navigation, suddenly the behavior changes and clicking on the MoveIt logo does not bring you to the MoveIt website homepage.

This adds that standardized functionality while maintaining the ability to return to the landing page via a new link in the top left.

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by BryceStevenWilley** [comment]
Don't quite agree with this change. The docs are clearly a different website (the header bar and style are all different), and it would be unintuitive for the logo link to traverse websites back to the MoveIt main page, where none of the document sublinks are. 

Another way to express this change might be to have the tutorial link on the website say `Tutorials (external)`. The tutorial logo image could also have the `Tutorials` subheader, instead of the `Planning Framework` that it currently does.

**Comment by simonGoldstein** [comment]
In the current mode I would describe the two as like 1.5 websites, linked but not separate. What my PR does is merge them more into one website while you seem to be suggesting we separate them into two more distinct websites. I can also totally see the value of moving in that direction instead. 
I can definitely swap these PRs with a pair that act like @BryceStevenWilley  described but I would want more input from people before I switch to new PRs.
@davetcoleman @robroboto Any opinions on which direction we should move in?

**Comment by robroboto** [comment]
I think some of the context is being lost here. 

The tutorials, while hosted at a different url, are still considered under the MoveIt framework and an integral part of the MoveIt website. Many resources of the main MoveIt site are useful for someone accessing the tutorials, and vice versa, so it makes sense that navigation is easy to navigate between the two.

The old moveit tutorial design ( http://docs.ros.org/kinetic/api/moveit_tutorials/html/index.html ) had a MoveIt logo which returns to the MoveIt site and there was also a tutorial home button. The UX was consistent across the MoveIt site, in that on any subpage or sublink, clicking the MoveIt logo returned you to the MoveIt homepage. 

The fetch page follows a similar style (https://docs.fetchrobotics.com/index.html).

This PR would address this current discrepancy by having both the MoveIt logo (which returns a user to https://moveit.ros.org/ ) and a tutorial home button (which returns a user to https://ros-planning.github.io/moveit_tutorials/

**Comment by BryceStevenWilley** [comment]
I think I understand better now, thanks for the explainations. I think of them as separate websites, but I see that most users probably don't. It would be pretty cool if we could somehow keep the same top bar from the main website too, but that's for another PR.

In that case, could we lose the `Planning Framework` span below the logo, so it's identical to the main website's?

**Comment by davetcoleman** [comment]
@simonGoldstein for changes like this, a screenshot of the change would be really helpful. overall looks good.

**Comment by simonGoldstein** [comment]
Here is a screenshot of the new top left of the website.
new_tutorial_home

**Comment by rhaschke** [comment]
To further emphasize the unity of both websites, I suggest:
- to insert the MoveIt Website into the breadcrumbs
- to remove the extra MoveIt Website link in the top right corner

Further, I like to keep the subtitle "Planning Framework" below the MoveIt logo.
And, finally, the search box, should read "Search tutorials" instead of "Search docs", because only the former are really searched...
I pushed appropriate commits to this PR branch.

image

**Comment by robroboto** [comment]
Great idea @rhaschke about the breadcrumbs and removing the extra website link

I'm not sure about keeping "planning framework" though.
- it's not used anywhere else on the MoveIt site in conjunction with the MoveIt logo, so it's inconsistent from a branding and UI perspective
- MoveIt has a greater scope than just planning, so to only call it a 'planning framework' may be somewhat misleading for new users (It's listed as a framework incorporating motion planning, manipulation, 3D perception, kinematics, control and navigation on the homepage for example )
- having both the 'planning framework' and adding a tutorials home button might clutter that space

what do you think?

**Comment by rhaschke** [comment]
@robroboto, I can understand and agree to your concerns. In this case, I suggest to drop both, "Planning Framework" and the tutorials home link below the logo. Everything can be reached via the breadcrumbs. I will push another commit for this.

**Comment by rhaschke** [comment]
Merged manually as 4aec05462c03ec0a43b432b3555a84e6ad1083bd due to conflicts.

**Pull request closed without merging**
