### PR TITLE
Re-added interact button image to visualization tutorial

### PR DESCRIPTION
**Pull request by jwhendy**
If helpful, re-added an image on how to add the `Interact` button if it didn't appear. This was originally added in #91 but was overwritten/reverted in #92. Committing to this branch didn't re-trigger the original build, so I think I need to re-PR.

### CODE REVIEW

**Comment by v4hn** [comment]
@jwhendy what's the state of this?

**Comment by jwhendy** [comment]
@v4hn I actually wasn't sure myself... per the comment, in PR #91 I added a screenshot of the way to add the interact button. Then PR #92 either intentionally or accidentally removed it. This PR would add it back.

I'd leave it up to you and the maintainers. It was originally merged in, so I thought it was considered potentially helpful. Then it was removed, so maybe it wasn't.

Did you mean what's the state of this PR in general, or the failing build checks? The failures seen to be the same I fixed in #109. If by "state"  you meant failing build, I'll rebase and see if I can make them go away!

**Comment by davetcoleman** [comment]
Travis passed, looks good to me.

**Comment by jwhendy** [comment]
@v4hn @davetcoleman So, the issue here is that I created two PRs on the same day. One fixed the issue that was causing a bunch of PRs to fail Travis... but because my branch didn't have that incorporated, this PR was still failing.

Is there a best practice for that? I'm new to git, and *definitely* new to PR protocol. I was under the assumption that I should keep branches dedicated to a single type of fix. If there's an unrelated error causing your build to fail, is it expected that you'll rebase/merge once that's brought into `upstream` and then re-commit?

---

Side question: when I re-commited, Travis said it was pending for at least an hour. I just decided to forget about it (and succeeded). It still says it's pending (which means it's been pending for 2 days now!)?



If I click the details link, though, I get this, which looks like it passed:



Any insight into this?

**Pull request merged**
