### PR TITLE
Update setup_assistant_tutorial.rst

### PR DESCRIPTION
**Pull request by crNewton**
fixed incorrect instruction

### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by davetcoleman** [comment]
@crNewton we don't officially support Kinetic anymore, but if you want this merged in please fix the unrelated broken hyperlink so that CI passes. You can just remove the link if you want. Thanks!

**Review by davetcoleman — COMMENTED** [review]
@crNewton we don't officially support Kinetic anymore, but if you want this merged in please fix the unrelated broken hyperlink so that CI passes. You can just remove the link if you want. Thanks!

**Comment by v4hn** [comment]
Actually, the virtual joint is part of the group in the tutorial, the images show that as well.
[The official configuration does not do that though](https://github.com/ros-planning/panda_moveit_config/blob/melodic-devel/config/panda_arm.xacro#L10).

I'm included to close this as wrong or did you actually experience a failure following the instructions @crNewton ?

**Comment by crNewton** [comment]
not sure which hyperlink is broken.

Yes there is a virtual_joint, but it's not supposed to be added as joint in the plan group.
(not even possible to add a virtual_joint to the plan group throug the setup wizard).

**Comment by v4hn** [comment]
>  (not even possible to add a virtual_joint to the plan group throug the setup wizard).

That statement is wrong as far as I can see. I just tried on `master`. Closing as wrong as mentioned above.
If you still think you are correct please create a new PR against the `master` branch and explain the errors you observe.

**Pull request closed without merging**
