### PR TITLE
Redesing tutorial page

### PR DESCRIPTION
**Pull request by L4co77**

### CODE REVIEW

**Comment by davetcoleman** [comment]
Great!

image

Questions:
- Shouldn't the "PLANNING FRAMEWORK" text be centered under the moveit logo?
- Can you add back a link in the top right that navigates back to the moveit homepage?

**Comment by L4co77** [comment]
done

**Comment by davetcoleman** [comment]
Sorry to nit-pick, but I think the font of "MoveIt! Website" should be same size of everything else (16px). Also could you remove some of the whitespace between "MoveIt! Website" and "Edit on Github"

I've reduced the font locally:
image

**Comment by L4co77** [comment]
> Sorry to nit-pick, but I think the font of "MoveIt! Website" should be same size of everything else (16px). Also could you remove some of the whitespace between "MoveIt! Website" and "Edit on Github"
> 
> I've reduced the font locally:
> image

done

**Pull request merged**
